//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.SingleSpaSample
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Data type.
    /// </summary>
    // *** Start programmer edit section *** (DataType CustomAttributes)

    // *** End programmer edit section *** (DataType CustomAttributes)
    public enum DataType
    {
        
        // *** Start programmer edit section *** (DataType.Anket CustomAttributes)

        // *** End programmer edit section *** (DataType.Anket CustomAttributes)
        Anket,
        
        // *** Start programmer edit section *** (DataType.News CustomAttributes)

        // *** End programmer edit section *** (DataType.News CustomAttributes)
        News,
        
        // *** Start programmer edit section *** (DataType.Dialogues CustomAttributes)

        // *** End programmer edit section *** (DataType.Dialogues CustomAttributes)
        Dialogues,
        
        // *** Start programmer edit section *** (DataType.CommentsOwn CustomAttributes)

        // *** End programmer edit section *** (DataType.CommentsOwn CustomAttributes)
        CommentsOwn,
        
        // *** Start programmer edit section *** (DataType.CommentsAbout CustomAttributes)

        // *** End programmer edit section *** (DataType.CommentsAbout CustomAttributes)
        CommentsAbout,
        
        // *** Start programmer edit section *** (DataType.Photo CustomAttributes)

        // *** End programmer edit section *** (DataType.Photo CustomAttributes)
        Photo,
        
        // *** Start programmer edit section *** (DataType.Video CustomAttributes)

        // *** End programmer edit section *** (DataType.Video CustomAttributes)
        Video,
        
        // *** Start programmer edit section *** (DataType.Other CustomAttributes)

        // *** End programmer edit section *** (DataType.Other CustomAttributes)
        Other,
    }
}
