//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.SingleSpaSample
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Person.
    /// </summary>
    // *** Start programmer edit section *** (Person CustomAttributes)

    // *** End programmer edit section *** (Person CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("PersonE", new string[] {
            "EsiaId as \'Esia id\'",
            "Name as \'Name\'",
            "MiddleName as \'Middle name\'",
            "Surname as \'Surname\'",
            "Birthday as \'Birthday\'",
            "Sex as \'Sex\'",
            "Reputation as \'Reputation\'"})]
    [AssociatedDetailViewAttribute("PersonE", "PersonAccount", "PersonAccountE", true, "", "Person account", true, new string[] {
            ""})]
    [View("PersonL", new string[] {
            "EsiaId as \'Esia id\'",
            "Name as \'Name\'",
            "MiddleName as \'Middle name\'",
            "Surname as \'Surname\'",
            "Birthday as \'Birthday\'",
            "Sex as \'Sex\'",
            "Reputation as \'Reputation\'"})]
    public class Person : ICSSoft.STORMNET.DataObject
    {
        
        private string fEsiaId;
        
        private string fName;
        
        private string fMiddleName;
        
        private string fSurname;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fBirthday;
        
        private TV.SingleSpaSample.Sex fSex;
        
        private int fReputation;
        
        private TV.SingleSpaSample.DetailArrayOfPersonAccount fPersonAccount;
        
        // *** Start programmer edit section *** (Person CustomMembers)

        // *** End programmer edit section *** (Person CustomMembers)

        
        /// <summary>
        /// EsiaId.
        /// </summary>
        // *** Start programmer edit section *** (Person.EsiaId CustomAttributes)

        // *** End programmer edit section *** (Person.EsiaId CustomAttributes)
        [StrLen(255)]
        public virtual string EsiaId
        {
            get
            {
                // *** Start programmer edit section *** (Person.EsiaId Get start)

                // *** End programmer edit section *** (Person.EsiaId Get start)
                string result = this.fEsiaId;
                // *** Start programmer edit section *** (Person.EsiaId Get end)

                // *** End programmer edit section *** (Person.EsiaId Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Person.EsiaId Set start)

                // *** End programmer edit section *** (Person.EsiaId Set start)
                this.fEsiaId = value;
                // *** Start programmer edit section *** (Person.EsiaId Set end)

                // *** End programmer edit section *** (Person.EsiaId Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Person.Name CustomAttributes)

        // *** End programmer edit section *** (Person.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Person.Name Get start)

                // *** End programmer edit section *** (Person.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Person.Name Get end)

                // *** End programmer edit section *** (Person.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Person.Name Set start)

                // *** End programmer edit section *** (Person.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Person.Name Set end)

                // *** End programmer edit section *** (Person.Name Set end)
            }
        }
        
        /// <summary>
        /// MiddleName.
        /// </summary>
        // *** Start programmer edit section *** (Person.MiddleName CustomAttributes)

        // *** End programmer edit section *** (Person.MiddleName CustomAttributes)
        [StrLen(255)]
        public virtual string MiddleName
        {
            get
            {
                // *** Start programmer edit section *** (Person.MiddleName Get start)

                // *** End programmer edit section *** (Person.MiddleName Get start)
                string result = this.fMiddleName;
                // *** Start programmer edit section *** (Person.MiddleName Get end)

                // *** End programmer edit section *** (Person.MiddleName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Person.MiddleName Set start)

                // *** End programmer edit section *** (Person.MiddleName Set start)
                this.fMiddleName = value;
                // *** Start programmer edit section *** (Person.MiddleName Set end)

                // *** End programmer edit section *** (Person.MiddleName Set end)
            }
        }
        
        /// <summary>
        /// Surname.
        /// </summary>
        // *** Start programmer edit section *** (Person.Surname CustomAttributes)

        // *** End programmer edit section *** (Person.Surname CustomAttributes)
        [StrLen(255)]
        public virtual string Surname
        {
            get
            {
                // *** Start programmer edit section *** (Person.Surname Get start)

                // *** End programmer edit section *** (Person.Surname Get start)
                string result = this.fSurname;
                // *** Start programmer edit section *** (Person.Surname Get end)

                // *** End programmer edit section *** (Person.Surname Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Person.Surname Set start)

                // *** End programmer edit section *** (Person.Surname Set start)
                this.fSurname = value;
                // *** Start programmer edit section *** (Person.Surname Set end)

                // *** End programmer edit section *** (Person.Surname Set end)
            }
        }
        
        /// <summary>
        /// Birthday.
        /// </summary>
        // *** Start programmer edit section *** (Person.Birthday CustomAttributes)

        // *** End programmer edit section *** (Person.Birthday CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime Birthday
        {
            get
            {
                // *** Start programmer edit section *** (Person.Birthday Get start)

                // *** End programmer edit section *** (Person.Birthday Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fBirthday;
                // *** Start programmer edit section *** (Person.Birthday Get end)

                // *** End programmer edit section *** (Person.Birthday Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Person.Birthday Set start)

                // *** End programmer edit section *** (Person.Birthday Set start)
                this.fBirthday = value;
                // *** Start programmer edit section *** (Person.Birthday Set end)

                // *** End programmer edit section *** (Person.Birthday Set end)
            }
        }
        
        /// <summary>
        /// Sex.
        /// </summary>
        // *** Start programmer edit section *** (Person.Sex CustomAttributes)

        // *** End programmer edit section *** (Person.Sex CustomAttributes)
        public virtual TV.SingleSpaSample.Sex Sex
        {
            get
            {
                // *** Start programmer edit section *** (Person.Sex Get start)

                // *** End programmer edit section *** (Person.Sex Get start)
                TV.SingleSpaSample.Sex result = this.fSex;
                // *** Start programmer edit section *** (Person.Sex Get end)

                // *** End programmer edit section *** (Person.Sex Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Person.Sex Set start)

                // *** End programmer edit section *** (Person.Sex Set start)
                this.fSex = value;
                // *** Start programmer edit section *** (Person.Sex Set end)

                // *** End programmer edit section *** (Person.Sex Set end)
            }
        }
        
        /// <summary>
        /// Reputation.
        /// </summary>
        // *** Start programmer edit section *** (Person.Reputation CustomAttributes)

        // *** End programmer edit section *** (Person.Reputation CustomAttributes)
        public virtual int Reputation
        {
            get
            {
                // *** Start programmer edit section *** (Person.Reputation Get start)

                // *** End programmer edit section *** (Person.Reputation Get start)
                int result = this.fReputation;
                // *** Start programmer edit section *** (Person.Reputation Get end)

                // *** End programmer edit section *** (Person.Reputation Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Person.Reputation Set start)

                // *** End programmer edit section *** (Person.Reputation Set start)
                this.fReputation = value;
                // *** Start programmer edit section *** (Person.Reputation Set end)

                // *** End programmer edit section *** (Person.Reputation Set end)
            }
        }
        
        /// <summary>
        /// Person.
        /// </summary>
        // *** Start programmer edit section *** (Person.PersonAccount CustomAttributes)

        // *** End programmer edit section *** (Person.PersonAccount CustomAttributes)
        public virtual TV.SingleSpaSample.DetailArrayOfPersonAccount PersonAccount
        {
            get
            {
                // *** Start programmer edit section *** (Person.PersonAccount Get start)

                // *** End programmer edit section *** (Person.PersonAccount Get start)
                if ((this.fPersonAccount == null))
                {
                    this.fPersonAccount = new TV.SingleSpaSample.DetailArrayOfPersonAccount(this);
                }
                TV.SingleSpaSample.DetailArrayOfPersonAccount result = this.fPersonAccount;
                // *** Start programmer edit section *** (Person.PersonAccount Get end)

                // *** End programmer edit section *** (Person.PersonAccount Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Person.PersonAccount Set start)

                // *** End programmer edit section *** (Person.PersonAccount Set start)
                this.fPersonAccount = value;
                // *** Start programmer edit section *** (Person.PersonAccount Set end)

                // *** End programmer edit section *** (Person.PersonAccount Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "PersonE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PersonE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PersonE", typeof(TV.SingleSpaSample.Person));
                }
            }
            
            /// <summary>
            /// "PersonL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PersonL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PersonL", typeof(TV.SingleSpaSample.Person));
                }
            }
        }
    }
}
