//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.SingleSpaSample
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Sex.
    /// </summary>
    // *** Start programmer edit section *** (Sex CustomAttributes)

    // *** End programmer edit section *** (Sex CustomAttributes)
    public enum Sex
    {
        
        // *** Start programmer edit section *** (Sex.Male CustomAttributes)

        // *** End programmer edit section *** (Sex.Male CustomAttributes)
        Male,
        
        // *** Start programmer edit section *** (Sex.Female CustomAttributes)

        // *** End programmer edit section *** (Sex.Female CustomAttributes)
        Female,
        
        // *** Start programmer edit section *** (Sex.Unknown CustomAttributes)

        // *** End programmer edit section *** (Sex.Unknown CustomAttributes)
        Unknown,
    }
}
