//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.SingleSpaSample
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Social network.
    /// </summary>
    // *** Start programmer edit section *** (SocialNetwork CustomAttributes)

    // *** End programmer edit section *** (SocialNetwork CustomAttributes)
    [AutoAltered()]
    [Caption("Social network")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SocialNetworkE", new string[] {
            "Name as \'Name\'"})]
    [View("SocialNetworkL", new string[] {
            "Name as \'Name\'"})]
    public class SocialNetwork : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (SocialNetwork CustomMembers)

        // *** End programmer edit section *** (SocialNetwork CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (SocialNetwork.Name CustomAttributes)

        // *** End programmer edit section *** (SocialNetwork.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (SocialNetwork.Name Get start)

                // *** End programmer edit section *** (SocialNetwork.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (SocialNetwork.Name Get end)

                // *** End programmer edit section *** (SocialNetwork.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SocialNetwork.Name Set start)

                // *** End programmer edit section *** (SocialNetwork.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (SocialNetwork.Name Set end)

                // *** End programmer edit section *** (SocialNetwork.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SocialNetworkE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SocialNetworkE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SocialNetworkE", typeof(TV.SingleSpaSample.SocialNetwork));
                }
            }
            
            /// <summary>
            /// "SocialNetworkL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SocialNetworkL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SocialNetworkL", typeof(TV.SingleSpaSample.SocialNetwork));
                }
            }
        }
    }
}
